version: "3.7"

services:
  web:
    image: danielbok/pcr-web
    ports:
      - "80:80"
    depends_on: 
      - server

  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pcrdb
    volumes:
      - pcrdb:/var/lib/postgresql/data
  
  server:
    image: danielbok/pcr-server
    ports:
      - "5050:5050"    
      - "5060:5060"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: 
      - postgres

volumes:
  pcrdb:
