admin:
  username: "admin"
  password: "password"

conda:
  # 'use' can only be 'shell' or 'docker'. Using 'shell' means that PCR will use a shell
  # version of conda to index the channels, using 'docker' will use a dockerized-conda instance
  # to index the channels. Use 'shell' when running the server application in a dockerized
  # container, like in docker-compose. This is because it is not easy to have a docker container
  # run another docker container whilst setting up the volumes for the second docker container.
  use: docker
  # if using docker, the image name and mount folder options can be specified
  image_name: danielbok/conda-repo-mgr
  mount_folder:  # leave empty for the application to automatically set path based on OS
  type: filesys

db:
  host: postgres
  port: 5432
  user: user
  password: password
  dbname: pcrdb

fileserver:
  port: 5050

application:
  port: 5060

decompressor:
  type: .tar.bz2  # leave this as the default, only used for testing purposes

# user checks and validation validation
user:
  # salt is used for password hashing so we don't save plaintext passwords in the database
  salt: "It is best to set this from the environment variable (PCR_USER.SALT=)"
  # email domain is the ending regex used to specify if you want a user/channel to come from a
  # certain domain. For example, if you want to only accept gmail only, you could use "gmail\..*$",
  # if you want gmail and hotmail you could use "(gmail|hotmail)\..*". Leave blank if you accept
  # all domains
  email_domain:

# if valid key and cert files are provided, server runs in HTTPS mode automatically
tls:
  cert:  # path to TLS certificate  (public key)
  key:  # path to TLS key (private key)
