admin:
  username: "admin"
  password: "password"

conda:
  image_name: danielbok/conda-repo-mgr
  mount_folder:  # leave empty for the application to automatically set path based on OS
  type: filesys

db:
  host: postgres
  port: 5432
  user: user
  password: password
  dbname: pcrdb
  type: postgres

repository:
  port: 5050

application:
  port: 5060

decompressor:
  type: .tar.bz2  # leave this as the default, only used for testing purposes

salt: "It is best to set this from the environment variable (PCR_SALT=)"
